- name: configure clientnode
  hosts: clientnode
  gather_facts: no


  vars_prompt:
  - name: hadoop_port
    prompt: "enter hadoop port"
    private: no
  - name: namenode_ip
    prompt: "enter namenode ip"
    private: no
  tasks:
  - name: copying java 
    copy:
            src: "/root/jdk-8u171-linux-x64.rpm"
            dest: "/root"

  - name: copying hadoop
    copy:
            src: "/root/hadoop-1.2.1-1.x86_64.rpm"
            dest: "/root"


  - name: installing java
    shell: "rpm -i /root/jdk-8u171-linux-x64.rpm"
    register: java_installed
    ignore_errors: yes
  - debug:
          var: java.stdout
  - name: installing hadoop
    shell: "rpm -ivh /root/hadoop-1.2.1-1.x86_64.rpm --force"
    register: hadoop_installed
    ignore_errors: yes
  - debug:
          var: hadoop_installed.stdout

  - name: copying core-site.xml
    template:
            src: "/root/hadoop/data/core-site.xml"
            dest: "/etc/hadoop/core-site.xml"
  - name: " Available files"
    shell: "hadoop fs -ls /"
    register: file
  - debug:
       var: file
  - name: "copying the file to client "
    copy:
       src: "/root/hadoop/inv.txt"
       dest: "/root"
  - name: "Uploading the file to namenode by client"
    shell: "hadoop fs -put /root/inv.txt /"
